### ISSUE TITLE
resize error

### ISSUE THREAD

**Issue by testwen00** [Rex-LK/ai_arm_learning#1]
root@ubuntu:~/work/demo/ai_arm_learning/x3/x3_inference/build# ./resize_demo RGB
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.5) /tmp/tmp.fAVojfHTaz/modules/imgproc/src/resize.cpp:3784: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Aborted

**Comment by testwen00** [comment]
换成绝对路径可以了

**Comment by Rex-LK** [comment]
ok
